### ISSUE TITLE
Get cache-busting to work

### ISSUE THREAD

**Issue by Melindrea** [Melindrea/smaty.se#7]
While it works to rev, I can't use the task to replace references, which is equally important

**Comment by akileez** [comment]
[gulp-rev-all](https://www.npmjs.com/package/gulp-rev-all) might be what you are looking for...
I had the same problem and desired a complete solution.

**Comment by Melindrea** [comment]
I'll check that up, thanks. Using gulp-rev it changed the filenames, but when I tried to use the reference files it didn't replace them in the other files, which ... kind of spoils the whole purpose!

**Comment by akileez** [comment]
glad it worked for you.
